### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by jmnovak50** [bloomkd46/homebridge-XfinityHome#1]
### Describe The Bug:

Pin does not allow for zero (0) prefixed codes.  eg. 0123 and config expects integer.

### To Reproduce:

Enter a zero prefixed pin and plugin does not start.  Not sure if the below error log is related

### Expected behavior:

Expect plugin to start without error.

### Logs:

```shell
[7/31/2021, 12:30:20 PM] TypeError: this.log is not a function
    at iControl._notifyError (/usr/lib/node_modules/homebridge-xfinityhome/iControl.js:521:10)
    at iControl.<anonymous> (/usr/lib/node_modules/homebridge-xfinityhome/iControl.js:257:14)
    at Request.self.callback (/usr/lib/node_modules/homebridge-xfinityhome/node_modules/request/request.js:185:22)
    at Request.emit (node:events:394:28)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-xfinityhome/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:394:28)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-xfinityhome/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:513:28)
    at IncomingMessage.emit (node:events:406:35)
    at endReadableNT (node:internal/streams/readable:1331:12)
```

### Config:

```shell
{
    "email": "XXXX@comcast.net",
    "password": "XXXX",
    "pin": 123,  <-- Entered 0123 in settings.  Tried with quotes
    "system": "XFINITY_HOME",
    "refresh_token": "cgmiyhcxxkbclgajrjaphi:APA91bEJqX8rPOjYQfIb_gtSCw7vsCjt8Y2ywANzzY5BISanPvriW35ohnwSzvSW20fVVwTGl6PDHi9dJi2_YGuIwGHPoLdFzPI6EPOmsXrXhGOI5RgWkkHwZqj8tWwP089pkH9IJjXI",
    "motion_accessories": true,
    "contact_accessories": true,
    "light_accessories": true,
    "panel_accessories": true,
    "camera_accessories": false,
    "device_info": false,
    "platform": "Xfinity Home"
}
```

### Node Version:

v16.6.0

### NPM Version:

7.19.1

### Homebridge Version:

1.3.4

### Operating System:

Raspberian

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/bloomkd46/homebridge-XfinityHome/blob/main/CODE_OF_CONDUCT.md)

**Comment by bloomkd46** [comment]
OK, I fixed the config problem and the logging problem happened to me in older versions, make sure you update the plugin to 1.3.1

**Comment by jmnovak50** [comment]
Thank you!  Updated and trying again!
