### ISSUE TITLE
Bug Report: Warnings on startup

### ISSUE THREAD

**Issue by rdeutsch3** [bloomkd46/homebridge-XfinityHome#14]
### Describe The Bug:

Restart Homebridge and system displays messages about unsupported devices (new since update to 3.x).

OS: Synology DSM

I've also got a number of accessory errors:
Master Glass Window Break: Unknown accessory!
Breakfast Windows: Unknown accessory!
Front Windows: Unknown accessory!
2nd Floor Windows: Unknown accessory!
Master Windows: Unknown accessory!
Living Windows: Unknown accessory!
Downstairs: Unknown accessory!
Upstairs: Unknown accessory!
Takeover: Unknown accessory!
Entry Doors: Unknown accessory!
Family Glass Window Break: Unknown accessory!

Should I log the each unknown accessory by type vs. each individually or all together in one issue?

### To Reproduce:

Restart Homebridge

### Expected behavior:

No error messages about unsupported devices

### Logs:

```shell
[[1/10/2023, 2:08:05 PM] [[[Xfinity Home][ Loaded 12 Accessories From Cache
[[1/10/2023, 2:08:06 PM] [Homebridge v1.6.0 (HAP v0.11.0) (Xfinity Home) is running on port 52433.
[[1/10/2023, 2:08:07 PM] [[[Xfinity Home][ [Restoring existing accessory from cache: Panel[
[[1/10/2023, 2:08:07 PM] [[[Xfinity Home][ [Panel: Server Started [
[[1/10/2023, 2:08:07 PM] [[[Xfinity Home][ [Restoring existing accessory from cache: Entry Doors[
[[1/10/2023, 2:08:07 PM] [[[Xfinity Home][ [Entry Doors: Server Started [
[[1/10/2023, 2:08:07 PM] [[[homebridge-xfinityhome][ This plugin generated a warning from the characteristic 'Manufacturer': characteristic value expected string and received undefined. See https://homebridge.io/w/JtMGR for more info.
[[1/10/2023, 2:08:07 PM] [[[[homebridge-xfinityhome][[ Error: [
[    at Manufacturer.Characteristic.characteristicWarning (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)[
[    at Manufacturer.Characteristic.validateUserInput (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2957:14)[
[    at Manufacturer.Characteristic.setValue (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2229:20)[
[    at AccessoryInformation.Service.setCharacteristic (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:758:35)[
[    at new Accessory (/volume1/homebridge/node_modules/homebridge-xfinityhome/src/accessories/Accessory.ts:67:8)[
[    at new UnknownAccessory (/volume1/homebridge/node_modules/homebridge-xfinityhome/src/accessories/UnknownAccessory.ts:15:5)[
[    at XfinityHomePlatform.discoverDevices (/volume1/homebridge/node_modules/homebridge-xfinityhome/src/platform.ts:172:19)[
[    at processTicksAndRejections (node:internal/process/task_queues:96:5)[
[[1/10/2023, 2:08:07 PM] [[[homebridge-xfinityhome][ This plugin generated a warning from the characteristic 'Model': characteristic value expected string and received undefined. See https://homebridge.io/w/JtMGR for more info.
[[1/10/2023, 2:08:07 PM] [[[[homebridge-xfinityhome][[ Error: [
[    at Model.Characteristic.characteristicWarning (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)[
[    at Model.Characteristic.validateUserInput (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2957:14)[
[    at Model.Characteristic.setValue (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2229:20)[
[    at AccessoryInformation.Service.setCharacteristic (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:758:35)[
[    at new Accessory (/volume1/homebridge/node_modules/homebridge-xfinityhome/src/accessories/Accessory.ts:69:8)[
[    at new UnknownAccessory (/volume1/homebridge/node_modules/homebridge-xfinityhome/src/accessories/UnknownAccessory.ts:15:5)[
[    at XfinityHomePlatform.discoverDevices (/volume1/homebridge/node_modules/homebridge-xfinityhome/src/platform.ts:172:19)[
[    at processTicksAndRejections (node:internal/process/task_queues:96:5)[
[[1/10/2023, 2:08:07 PM] [[[homebridge-xfinityhome][ This plugin generated a warning from the characteristic 'Firmware Revision': characteristic value expected string and received undefined. See https://homebridge.io/w/JtMGR for more info.
[[1/10/2023, 2:08:07 PM] [[[[homebridge-xfinityhome][[ Error: [
[    at FirmwareRevision.Characteristic.characteristicWarning (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)[
[    at FirmwareRevision.Characteristic.validateUserInput (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2957:14)[
[    at FirmwareRevision.Characteristic.setValue (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2229:20)[
[    at AccessoryInformation.Service.setCharacteristic (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:758:35)[
[    at new Accessory (/volume1/homebridge/node_modules/homebridge-xfinityhome/src/accessories/Accessory.ts:71:8)[
[    at new UnknownAccessory (/volume1/homebridge/node_modules/homebridge-xfinityhome/src/accessories/UnknownAccessory.ts:15:5)[
[    at XfinityHomePlatform.discoverDevices (/volume1/homebridge/node_modules/homebridge-xfinityhome/src/platform.ts:172:19)[
[    at processTicksAndRejections (node:internal/process/task_queues:96:5)[
[[1/10/2023, 2:08:07 PM] [[[Xfinity Home][ [Entry Doors: Unknown accessory! [
[[1/10/2023, 2:08:07 PM] [[[Xfinity Home][ [Entry Doors: Please open an issue about this. [
[[1/10/2023, 2:08:07 PM] [[[Xfinity Home][ [Entry Doors: {[
[  "hardwareId": "113",[
[  "status": "online",[
[  "technology": "legacyAlarmPanel",[
[  "_links": {[
[    "self": {[
[      "href": "/client/icontrol/device/113"[
[    },[
[    "isBypassed": {[
[      "method": "POST",[
[      "href": "network/instances/113.0/points/isBypassed"[
[    },[
[    "label": {[
[      "method": "POST",[
[      "href": "network/instances/113.0/points/label"[
[    },[
[    "functionType": {[
[      "method": "POST",[
[      "href": "network/instances/113.0/points/functionType"[
[    }[
[  },[
[  "deletable": true,[
[  "deviceType": "sensor",[
[  "properties": {[
[    "isFaulted": false,[
[    "displayOrder": 1,[
[    "isBypassed": false,[
[    "label": "Entry Doors",[
[    "functionType": "entryExit",[
[    "type": "door"[
[  },[
[  "name": "Entry Doors",[
[  "id": "113.0",[
[  "deviceSubtype": "default",[
[  "trouble": [][
[} [
[[1/10/2023, 2:08:07 PM] [[[Xfinity Home][ [Restoring existing accessory from cache: Master Glass Window Break[
[[1/10/2023, 2:08:07 PM] [[[Xfinity Home][ [Master Glass Window Break: Server Started [
[[1/10/2023, 2:08:07 PM] [[[homebridge-xfinityhome][ This plugin generated a warning from the characteristic 'Manufacturer': characteristic value expected string and received undefined. See https://homebridge.io/w/JtMGR for more info.
[[1/10/2023, 2:08:07 PM] [[[[homebridge-xfinityhome][[ Error: [
[    at Manufacturer.Characteristic.characteristicWarning (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)[
[    at Manufacturer.Characteristic.validateUserInput (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2957:14)[
[    at Manufacturer.Characteristic.setValue (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2229:20)[
[    at AccessoryInformation.Service.setCharacteristic (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:758:35)[
[    at new Accessory (/volume1/homebridge/node_modules/homebridge-xfinityhome/src/accessories/Accessory.ts:67:8)[
[    at new UnknownAccessory (/volume1/homebridge/node_modules/homebridge-xfinityhome/src/accessories/UnknownAccessory.ts:15:5)[
[    at XfinityHomePlatform.discoverDevices (/volume1/homebridge/node_modules/homebridge-xfinityhome/src/platform.ts:172:19)[
[    at processTicksAndRejections (node:internal/process/task_queues:96:5)[
[[1/10/2023, 2:08:07 PM] [[[homebridge-xfinityhome][ This plugin generated a warning from the characteristic 'Model': characteristic value expected string and received undefined. See https://homebridge.io/w/JtMGR for more info.
[[1/10/2023, 2:08:07 PM] [[[[homebridge-xfinityhome][[ Error: [
[    at Model.Characteristic.characteristicWarning (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)[
[    at Model.Characteristic.validateUserInput (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2957:14)[
[    at Model.Characteristic.setValue (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2229:20)[
[    at AccessoryInformation.Service.setCharacteristic (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:758:35)[
[    at new Accessory (/volume1/homebridge/node_modules/homebridge-xfinityhome/src/accessories/Accessory.ts:69:8)[
[    at new UnknownAccessory (/volume1/homebridge/node_modules/homebridge-xfinityhome/src/accessories/UnknownAccessory.ts:15:5)[
[    at XfinityHomePlatform.discoverDevices (/volume1/homebridge/node_modules/homebridge-xfinityhome/src/platform.ts:172:19)[
[    at processTicksAndRejections (node:internal/process/task_queues:96:5)[
[[1/10/2023, 2:08:07 PM] [[[homebridge-xfinityhome][ This plugin generated a warning from the characteristic 'Firmware Revision': characteristic value expected string and received undefined. See https://homebridge.io/w/JtMGR for more info.
[[1/10/2023, 2:08:07 PM] [[[[homebridge-xfinityhome][[ Error: [
[    at FirmwareRevision.Characteristic.characteristicWarning (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)[
[    at FirmwareRevision.Characteristic.validateUserInput (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2957:14)[
[    at FirmwareRevision.Characteristic.setValue (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2229:20)[
[    at AccessoryInformation.Service.setCharacteristic (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:758:35)[
[    at new Accessory (/volume1/homebridge/node_modules/homebridge-xfinityhome/src/accessories/Accessory.ts:71:8)[
[    at new UnknownAccessory (/volume1/homebridge/node_modules/homebridge-xfinityhome/src/accessories/UnknownAccessory.ts:15:5)[
[    at XfinityHomePlatform.discoverDevices (/volume1/homebridge/node_modules/homebridge-xfinityhome/src/platform.ts:172:19)[
[    at processTicksAndRejections (node:internal/process/task_queues:96:5)[
```

### Config:

```shell
{
    "bridge": {
        "name": "ZZZ",
        "username": "0E:EE:84:98:C2:5B",
        "port": 51810,
        "pin": "255-19-737",
        "advertiser": "bonjour-hap",
        "bind": [
            "bond0"
        ]
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "Xfinity Home",
            "refreshToken": ******
            "pin": "1597",
            "temperatureSensors": true,
            "logLevel": 3,
            "logWatchdogErrors": false,
            "_bridge": {
                "username": "0E:CA:A4:35:02:C7",
                "port": 52433
            },
            "platform": "XfinityHomePlatform"
        }
    ]
}
```

### Operating System:

Other

### Node Version:

v16.16.0

### NPM Version:

8.11.0

### Homebridge Version:

1.6.0

### Plugin Version:

3.0.4

**Comment by bloomkd46** [comment]
> Should I log the each unknown accessory by type vs. each individually or all together in one issue?

please open a separate issue for each type of device.

**Comment by rdeutsch3** [comment]
Logged the following:
Windows -> https://github.com/bloomkd46/homebridge-XfinityHome/issues/15
Glass Break -> https://github.com/bloomkd46/homebridge-XfinityHome/issues/16
Smoke Detectors -> https://github.com/bloomkd46/homebridge-XfinityHome/issues/17
Doors -> https://github.com/bloomkd46/homebridge-XfinityHome/issues/18
Takeover -> https://github.com/bloomkd46/homebridge-XfinityHome/issues/19

They are mostly copy/paste with the relevant sections copied out from the same log as this one.

**Comment by bloomkd46** [comment]
Will solve issues individually
