### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by woodpile-parker** [bloomkd46/homebridge-XfinityHome#40]
### Describe The Bug:

Error loading the Xfinity plugin after installing Pi updates

### To Reproduce:

With the plugin enabled, after restarting Homebridge I get the following error message and Homebridge gets into a restart loop:

[1/14/2024, 11:14:59 AM] Error: Request failed with status code 400
    at createError (/var/lib/homebridge/node_modules/homebridge-xfinityhome/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/var/lib/homebridge/node_modules/homebridge-xfinityhome/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/var/lib/homebridge/node_modules/homebridge-xfinityhome/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1400:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) @

### Expected behavior:

Expected Homebridge to successfully load the plugin

### Logs:

```shell
More on the error messaging noted above:

[1/14/2024, 11:50:40 AM] Homebridge v1.7.0 (HAP v0.11.1) (Homebridge 661B) is running on port 51272.
[1/14/2024, 11:50:40 AM] Error: Request failed with status code 400
    at createError (/var/lib/homebridge/node_modules/homebridge-xfinityhome/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/var/lib/homebridge/node_modules/homebridge-xfinityhome/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/var/lib/homebridge/node_modules/homebridge-xfinityhome/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:530:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
[1/14/2024, 11:50:40 AM] Got SIGTERM, shutting down Homebridge...
[1/14/2024, 11:50:40 AM] [B-Hyve] Child bridge process ended
[1/14/2024, 11:50:40 AM] [B-Hyve] Process Ended. Code: null, Signal: SIGTERM
[1/14/2024, 11:50:41 AM] [Ring] Found the following locations:
[1/14/2024, 11:50:41 AM] [Ring]   locationId: c22ywb-3sj0f-0 - Seattle
[1/14/2024, 11:50:41 AM] [Ring] Configuring 3 cameras and 3 devices for location "Seattle" - locationId: c22ywb-3sj0f-0
[1/14/2024, 11:50:45 AM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[1/14/2024, 11:50:50 AM] [HB Supervisor] Restarting Homebridge...
[1/14/2024, 11:50:50 AM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution
[1/14/2024, 11:50:50 AM] [HB Supervisor] Started Homebridge v1.7.0 with PID: 2734
[1/14/2024, 11:50:52 AM] Loaded config.json with 0 accessories and 5 platforms.
[1/14/2024, 11:50:52 AM] Loaded 3 cached accessories from cachedAccessories.
[1/14/2024, 11:50:52 AM] ---
[1/14/2024, 11:50:52 AM] Disabled plugin: homebridge-myq@3.4.2
[1/14/2024, 11:50:52 AM] ---
[1/14/2024, 11:50:52 AM] Loaded plugin: homebridge-orbit-irrigation@1.2.28
[1/14/2024, 11:50:52 AM] Registering platform 'homebridge-orbit-irrigation.bhyve'
[1/14/2024, 11:50:52 AM] ---
[1/14/2024, 11:50:54 AM] Loaded plugin: homebridge-ring@12.0.1
[1/14/2024, 11:50:54 AM] Registering platform 'homebridge-ring.Ring'
[1/14/2024, 11:50:54 AM] ---
[1/14/2024, 11:50:55 AM] Loaded plugin: homebridge-xfinityhome@3.4.1
[1/14/2024, 11:50:55 AM] Registering platform 'homebridge-xfinityhome.XfinityHomePlatform'
[1/14/2024, 11:50:55 AM] ---
[1/14/2024, 11:50:55 AM] Loading 5 platforms...
[1/14/2024, 11:50:55 AM] [Ring] Initializing Ring platform...
[1/14/2024, 11:50:55 AM] Ignoring config for the platform "myQ" in your config.json as the plugin "homebridge-myq" has been disabled.
[1/14/2024, 11:50:55 AM] [Xfinity Home] Initializing XfinityHomePlatform platform...
[1/14/2024, 11:50:55 AM] [B-Hyve] Initializing bhyve platform...
[1/14/2024, 11:50:55 AM] [B-Hyve] Initializing child bridge 0E:D3:7E:6B:57:C0
[1/14/2024, 11:50:55 AM] [Ring] Configuring cached accessory 476bda64-f383-43e2-a7a7-c743732a94e9 Front Door
[1/14/2024, 11:50:55 AM] [Ring] Configuring cached accessory fdc6234b-713d-4cd5-83e8-066265be1000 Parking Space
[1/14/2024, 11:50:55 AM] [Ring] Configuring cached accessory 575d261f-3bea-4c1d-ab60-05b0075ae281 Side
[1/14/2024, 11:50:55 AM] [Xfinity Home] Using Refresh Token From Config: ***
[1/14/2024, 11:50:55 AM] [Xfinity Home] Loaded 0 Accessories From Cache
Setup Payload:
X-HM://0024H7TE12J30
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 609-44-777 │     
    └────────────┘     
                       
[1/14/2024, 11:50:55 AM] Homebridge v1.7.0 (HAP v0.11.1) (Homebridge 661B) is running on port 51272.
[1/14/2024, 11:50:55 AM] Error: Request failed with status code 400
    at createError (/var/lib/homebridge/node_modules/homebridge-xfinityhome/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/var/lib/homebridge/node_modules/homebridge-xfinityhome/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/var/lib/homebridge/node_modules/homebridge-xfinityhome/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:530:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
[1/14/2024, 11:50:55 AM] Got SIGTERM, shutting down Homebridge...
```

### Config:

```shell
{
    "name": "Xfinity Home",
    "refreshToken": "***",
    "pin": "****",
    "logLevel": 3,
    "platform": "XfinityHomePlatform"
}
```

### Operating System:

Raspberian

### Node Version:

20.11.0 (also seeing on 18.x)

### NPM Version:

10.2.4

### Homebridge Version:

1.7.0

### Plugin Version:

3.4.1

**Comment by bloomkd46** [comment]
Fixed v3.4.2
