### ISSUE TITLE
Having issues with proxy tool

### ISSUE THREAD

**Issue by woodpile-parker** [bloomkd46/homebridge-XfinityHome#8]
### Describe Your Problem:

Hey there - I'm struggling with the proxy tool and I'm sure it's user error.  I've installed the cert but once I configure the proxy on my wifi network, I immediately lose internet connectivity, which prevents me from logging into Xfinity Home.  I've tried on multiple devices, but again, sure I'm doing something wrong.  Any tips?  Let me know if I can provide more detailed repro steps.  Thanks.

### Logs:

```shell
[11/6/2022, 8:15:40 AM] [Homebridge UI] [homebridge-xfinityhome] Incoming Request: /startProxy
[11/6/2022, 8:15:41 AM] [Homebridge UI] [homebridge-xfinityhome] Incoming Request: /proxyActive
[11/6/2022, 8:16:08 AM] [Homebridge UI] [homebridge-xfinityhome] Terminating child process...
[11/6/2022, 8:16:08 AM] [Homebridge UI] [homebridge-xfinityhome] Child process ended
[11/6/2022, 8:17:43 AM] [Homebridge UI] Changes to config.json saved.
[11/6/2022, 8:17:44 AM] [Homebridge UI] Running Command: sudo -E -n npm uninstall -g homebridge-xfinityhome
[11/6/2022, 8:18:03 AM] [Homebridge UI] Running Command: sudo -E -n npm install -g homebridge-xfinityhome@2.4.0
[11/6/2022, 8:19:57 AM] [Homebridge UI] [homebridge-xfinityhome] Incoming Request: /startProxy
[11/6/2022, 8:19:57 AM] [Homebridge UI] [homebridge-xfinityhome] Incoming Request: /proxyActive
[11/6/2022, 8:20:39 AM] [Homebridge UI] [homebridge-xfinityhome] Incoming Request: /token
[11/6/2022, 8:20:52 AM] [Homebridge UI] [homebridge-xfinityhome] node:internal/tls/secure-context:69
    context.setCert(cert);
            ^

Error: error:0909006C:PEM routines:get_name:no start line
    at node:internal/tls/secure-context:69:13
    at Array.forEach (<anonymous>)
    at setCerts (node:internal/tls/secure-context:67:3)
    at configSecureContext (node:internal/tls/secure-context:156:5)
    at Object.createSecureContext (node:_tls_common:121:3)
    at Server.setSecureContext (node:_tls_wrap:1353:27)
    at Server (node:_tls_wrap:1212:8)
    at new Server (node:https:73:3)
    at Object.createServer (node:https:109:10)
    at Proxy._createHttpsServer (/usr/lib/node_modules/homebridge-xfinityhome/node_modules/http-mitm-proxy/lib/proxy.js:106:27) {
  library: 'PEM routines',
  function: 'get_name',
  reason: 'no start line',
  code: 'ERR_OSSL_PEM_NO_START_LINE'
}
[11/6/2022, 8:20:52 AM] [Homebridge UI] [homebridge-xfinityhome] Child process ended
[11/6/2022, 8:21:28 AM] [Homebridge UI] [homebridge-xfinityhome] Terminating child process...
[11/6/2022, 8:22:29 AM] [Homebridge UI] [homebridge-xfinityhome] Incoming Request: /startProxy
[11/6/2022, 8:22:30 AM] [Homebridge UI] [homebridge-xfinityhome] Incoming Request: /proxyActive
[11/6/2022, 8:23:04 AM] [Homebridge UI] Changes to config.json saved.
[11/6/2022, 8:23:04 AM] [Homebridge UI] [homebridge-xfinityhome] Terminating child process...
[11/6/2022, 8:23:04 AM] [Homebridge UI] [homebridge-xfinityhome] Child process ended
[11/6/2022, 8:23:20 AM] [Homebridge UI] [homebridge-xfinityhome] Incoming Request: /startProxy
[11/6/2022, 8:23:20 AM] [Homebridge UI] [homebridge-xfinityhome] Incoming Request: /proxyActive
[11/6/2022, 8:23:22 AM] [Homebridge UI] [homebridge-xfinityhome] Incoming Request: /token
[11/6/2022, 8:23:28 AM] [Homebridge UI] [homebridge-xfinityhome] node:internal/tls/secure-context:69
    context.setCert(cert);
            ^

Error: error:0909006C:PEM routines:get_name:no start line
    at node:internal/tls/secure-context:69:13
    at Array.forEach (<anonymous>)
    at setCerts (node:internal/tls/secure-context:67:3)
    at configSecureContext (node:internal/tls/secure-context:156:5)
    at Object.createSecureContext (node:_tls_common:121:3)
    at Server.setSecureContext (node:_tls_wrap:1353:27)
    at Server (node:_tls_wrap:1212:8)
    at new Server (node:https:73:3)
    at Object.createServer (node:https:109:10)
    at Proxy._createHttpsServer (/usr/lib/node_modules/homebridge-xfinityhome/node_modules/http-mitm-proxy/lib/proxy.js:106:27) {
  library: 'PEM routines',
  function: 'get_name',
  reason: 'no start line',
  code: 'ERR_OSSL_PEM_NO_START_LINE'
}
[11/6/2022, 8:23:28 AM] [Homebridge UI] [homebridge-xfinityhome] Child process ended
[11/6/2022, 8:24:04 AM] [Homebridge UI] [homebridge-xfinityhome] Terminating child process...
[11/6/2022, 8:24:25 AM] [Homebridge UI] [homebridge-xfinityhome] Incoming Request: /startProxy
[11/6/2022, 8:24:26 AM] [Homebridge UI] [homebridge-xfinityhome] Incoming Request: /proxyActive
[11/6/2022, 8:24:46 AM] [Homebridge UI] [homebridge-xfinityhome] Incoming Request: /token
[11/6/2022, 8:24:53 AM] [Homebridge UI] [homebridge-xfinityhome] node:internal/tls/secure-context:69
    context.setCert(cert);
            ^

Error: error:0909006C:PEM routines:get_name:no start line
    at node:internal/tls/secure-context:69:13
    at Array.forEach (<anonymous>)
    at setCerts (node:internal/tls/secure-context:67:3)
    at configSecureContext (node:internal/tls/secure-context:156:5)
    at Object.createSecureContext (node:_tls_common:121:3)
    at Server.setSecureContext (node:_tls_wrap:1353:27)
    at Server (node:_tls_wrap:1212:8)
    at new Server (node:https:73:3)
    at Object.createServer (node:https:109:10)
    at Proxy._createHttpsServer (/usr/lib/node_modules/homebridge-xfinityhome/node_modules/http-mitm-proxy/lib/proxy.js:106:27) {
  library: 'PEM routines',
  function: 'get_name',
  reason: 'no start line',
  code: 'ERR_OSSL_PEM_NO_START_LINE'
}
[11/6/2022, 8:24:53 AM] [Homebridge UI] [homebridge-xfinityhome] Child process ended
[11/6/2022, 8:25:46 AM] [Homebridge UI] [homebridge-xfinityhome] Terminating child process...
```

### Config:

```shell
{
            "email": "*****",
            "password": "*****",
            "pin": "****",
            "system": "XFINITY_HOME",
            "refresh_token": "token=fZGkx1nRzUGVpURm_uXjm1:APA91bGADvrWUF2qwj9b94FtLRtxveAVxhqwcoAt2zO6ruGakFw2QwK-ctcW5zO-6tAfIMOqy26-GUct7T1uBMT4XkDvJi_nYjqaBDdjtLJPwjzAZGbNhpByWPpJTgYfHbYam3twn-02",
            "motion_accessories": true,
            "contact_accessories": true,
            "light_accessories": true,
            "panel_accessories": true,
            "camera_accessories": false,
            "device_info": false,
            "platform": "Xfinity Home"
        },
```

### Operating System:

Debian

### Node Version:

16.18.1

### NPM Version:

8.19.2

### Homebridge Version:

1.5.1

### Plugin Version:

2.4.0

**Comment by bloomkd46** [comment]
Closed due to inactivity, please comment to re-open
